/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChapterRow: typeof import('./src/components/Modules/Chapters/ChapterRow.vue')['default']
    DsBackButton: typeof import('./src/components/DsSystem/DsBackButton.vue')['default']
    DsButton: typeof import('./src/components/DsSystem/DsButton.vue')['default']
    DsCheckIcon: typeof import('./src/components/DsSystem/DsCheckIcon.vue')['default']
    DsMenu: typeof import('./src/components/DsSystem/DsMenu.vue')['default']
    DsMultiselect: typeof import('./src/components/DsSystem/DsMultiselect.vue')['default']
    DsSlider: typeof import('./src/components/DsSystem/DsSlider.vue')['default']
    DsUpdateBanner: typeof import('./src/components/DsSystem/DsUpdateBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
